# Generated by Django 5.0.7 on 2025-12-21 23:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('includes', models.TextField(blank=True, default='', help_text='Строки, которые точно входят', verbose_name='Входит')),
                ('excludes', models.TextField(blank=True, default='', help_text='Строки, которые точно НЕ входят', verbose_name='Не входит')),
                ('borderline', models.TextField(blank=True, default='', help_text='Пограничные строки', verbose_name='Граница')),
                ('is_leaf', models.BooleanField(db_index=True, default=True, verbose_name='Листовая категория')),
                ('level', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Уровень иерархии')),
                ('path', models.CharField(blank=True, db_index=True, default='', max_length=500, verbose_name='Путь')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('category', models.ForeignKey(limit_choices_to={'is_leaf': True}, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.category', verbose_name='Категория')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
                'ordering': ['sku'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_leaf', 'level'], name='catalog_cat_is_leaf_8d0f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['path'], name='catalog_cat_path_dea278_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['sku'], name='catalog_ite_sku_0b70c9_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='catalog_ite_categor_e8b6f8_idx'),
        ),
    ]
