# Generated by Django 5.0.7 on 2025-12-21 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код проекта')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('status', models.CharField(choices=[('planned', 'План'), ('active', 'В работе'), ('paused', 'Пауза'), ('done', 'Завершён')], default='planned', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата старта')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Шаблон этапов',
                'verbose_name_plural': 'Шаблоны этапов',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='№')),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('status', models.CharField(choices=[('planned', 'План'), ('in_progress', 'В работе'), ('done', 'Готово'), ('canceled', 'Отменён')], default='planned', max_length=20, verbose_name='Статус')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='План. старт')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='План. завершение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Этап проекта',
                'verbose_name_plural': 'Этапы проекта',
                'ordering': ['project', 'order', 'id'],
                'unique_together': {('project', 'order')},
            },
        ),
        migrations.CreateModel(
            name='StageTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='№')),
                ('name', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('default_duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, дни')),
                ('default_offset_days', models.IntegerField(blank=True, null=True, verbose_name='Смещение старта от даты проекта, дни')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='projects.stagetemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Этап в шаблоне',
                'verbose_name_plural': 'Этапы в шаблоне',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Код задачи')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование задачи')),
                ('start_planned', models.DateField(blank=True, null=True, verbose_name='План. старт')),
                ('finish_planned', models.DateField(blank=True, null=True, verbose_name='План. финиш')),
                ('start_fact', models.DateField(blank=True, null=True, verbose_name='Факт. старт')),
                ('finish_fact', models.DateField(blank=True, null=True, verbose_name='Факт. финиш')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='projects.task', verbose_name='Родительская задача')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Проект')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projectstage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Задача/подзадача',
                'verbose_name_plural': 'Задачи/подзадачи',
                'ordering': ['project__code', 'code'],
                'unique_together': {('project', 'code')},
            },
        ),
    ]
