# Generated by Django 5.0.7 on 2025-12-21 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True, verbose_name='№ заказа')),
                ('status', models.CharField(default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Заказ поставщику',
                'verbose_name_plural': 'Заказы поставщикам',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Статус')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item', verbose_name='Номенклатура')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaseorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Строка заказа',
                'verbose_name_plural': 'Строки заказа',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('open', 'Открыта'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('requested_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Кто создал')),
                ('comment', models.TextField(blank=True, db_column='note', default='', verbose_name='Примечание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='projects.project', verbose_name='Проект')),
                ('project_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='projects.projectstage', verbose_name='Этап проекта')),
            ],
            options={
                'verbose_name': 'Заявка на закупку',
                'verbose_name_plural': 'Заявки на закупку',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Количество')),
                ('need_date', models.DateField(blank=True, null=True, verbose_name='Необходимо к')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'В обработке'), ('awarded', 'Выполнено'), ('delivered', 'Доставлено')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('priority', models.CharField(blank=True, default='normal', max_length=20, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item', verbose_name='Номенклатура')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaserequest', verbose_name='Заявка')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_lines', to='projects.task', verbose_name='Задача')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit', verbose_name='Единица')),
            ],
            options={
                'verbose_name': 'Строка заявки',
                'verbose_name_plural': 'Строки заявки',
                'ordering': ['request', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Путь к файлу')),
                ('source', models.CharField(blank=True, default='', max_length=255, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('purchase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='procurement.purchaserequest', verbose_name='Заявка')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'КП',
                'verbose_name_plural': 'КП',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_sku', models.CharField(blank=True, default='', max_length=255, verbose_name='Артикул поставщика')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
                ('lead_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок поставки (дн.)')),
                ('moq_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='МОЗ')),
                ('pack_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Упаковка')),
                ('lot_step', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Шаг лота')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item', verbose_name='Номенклатура')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.quote', verbose_name='КП')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit', verbose_name='Единица')),
            ],
            options={
                'verbose_name': 'Строка КП',
                'verbose_name_plural': 'Строки КП',
            },
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('pack_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Кол-во в упаковке')),
                ('lead_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок поставки (дн.)')),
                ('moq_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='МОЗ')),
                ('lot_step', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Шаг лота')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='Номенклатура')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'История цены',
                'verbose_name_plural': 'История цен',
                'ordering': ['-dt', 'item__sku'],
                'indexes': [models.Index(fields=['item', '-dt'], name='procurement_item_id_234bb8_idx'), models.Index(fields=['supplier', '-dt'], name='procurement_supplie_a6bdeb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status'], name='procurement_status_4e1362_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['project'], name='procurement_project_f628f3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['deadline'], name='procurement_deadlin_848c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestline',
            index=models.Index(fields=['request', 'status'], name='procurement_request_e4ca21_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestline',
            index=models.Index(fields=['item'], name='procurement_item_id_47f6dc_idx'),
        ),
    ]
