# Generated by Django 5.0.7 on 2026-03-03 07:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('procurement', '0006_shipments_split'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='itemsuppliermapping',
            new_name='procurement_item_id_ade3dc_idx',
            old_name='procurement_item_active_idx',
        ),
        migrations.RenameIndex(
            model_name='itemsuppliermapping',
            new_name='procurement_price_l_deae01_idx',
            old_name='procurement_pricelist_line_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierpricelist',
            new_name='procurement_supplie_5c2f4d_idx',
            old_name='procurement_supplier_active_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierpricelist',
            new_name='procurement_effecti_f13648_idx',
            old_name='procurement_effective_expiry_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierpricelistline',
            new_name='procurement_price_l_a175b9_idx',
            old_name='procurement_pricelist_available_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierpricelistline',
            new_name='procurement_supplie_ce7a32_idx',
            old_name='procurement_supplier_sku_idx',
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Исключено из закупки'),
        ),
        migrations.AlterField(
            model_name='itemsuppliermapping',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=1, help_text='\n        Коэффициент преобразования между единицами Item и SupplierPriceListLine.\n        \n        Примеры:\n        - Item в шт, Supplier в шт: коэф = 1.0\n        - Item в шт, Supplier в упаковках по 500 шт: коэф = 500.0\n        - Item в м³, Supplier в м³: коэф = 1.0\n        - Item в кг, Supplier в тоннах: коэф = 1000.0\n        \n        При заказе: supplier_qty = item_qty * conversion_factor\n        ', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='itemsuppliermapping',
            name='is_preferred',
            field=models.BooleanField(default=False, help_text='Предпочитаемый поставщик для этого Item (используется при сортировке)'),
        ),
        migrations.AlterField(
            model_name='itemsuppliermapping',
            name='item',
            field=models.ForeignKey(help_text='Внутренний Item из каталога', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_mappings', to='catalog.item'),
        ),
        migrations.AlterField(
            model_name='itemsuppliermapping',
            name='min_quantity_override',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Переопределить МОК из прайс-листа (в единицах Item). NULL = использовать из прайс-листа', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='itemsuppliermapping',
            name='price_list_line',
            field=models.ForeignKey(help_text='Позиция в прайс-листе поставщика', on_delete=django.db.models.deletion.CASCADE, related_name='item_mappings', to='procurement.supplierpricelistline'),
        ),
        migrations.AlterField(
            model_name='supplierpricelistline',
            name='vat_included',
            field=models.BooleanField(default=False, help_text='Включена ли цена цена цены НДС (если False - цена без НДС)'),
        ),
        migrations.AlterField(
            model_name='supplierpricelistline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Ставка НДС в процентах (обычно 20, 10, 0)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MinValueValidator(Decimal('100'))]),
        ),
    ]
