# Generated by Django 5.0.7 on 2026-03-03 07:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_rename_procurement_item_active_idx_procurement_item_id_ade3dc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpricelistline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Ставка НДС в процентах (обычно 20, 10, 0)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
