# Generated by ChatGPT on 2026-03-09

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    PurchaseOrder = apps.get_model("procurement", "PurchaseOrder")
    Shipment = apps.get_model("procurement", "Shipment")

    # Backfill PurchaseOrder.project/project_stage from linked PurchaseRequest
    # and (if needed) derive project from project_stage.
    for po in PurchaseOrder.objects.select_related("purchase_request", "project_stage").all():
        update = []

        pr = getattr(po, "purchase_request", None)
        if po.project_id is None:
            pr_project_id = getattr(pr, "project_id", None) if pr else None
            if pr_project_id:
                po.project_id = pr_project_id
                update.append("project")

        if po.project_stage_id is None:
            pr_stage_id = getattr(pr, "project_stage_id", None) if pr else None
            if pr_stage_id:
                po.project_stage_id = pr_stage_id
                update.append("project_stage")

        # If project still empty, but stage exists — infer project from stage
        if po.project_id is None and po.project_stage_id is not None:
            st = getattr(po, "project_stage", None)
            st_project_id = getattr(st, "project_id", None) if st else None
            if st_project_id:
                po.project_id = st_project_id
                update.append("project")

        if update:
            po.save(update_fields=update)

    # Backfill Shipment.project/project_stage from order snapshot, then from order.purchase_request
    for sh in Shipment.objects.select_related("order", "order__purchase_request", "order__project_stage", "project_stage").all():
        update = []
        po = getattr(sh, "order", None)
        pr = getattr(po, "purchase_request", None) if po else None

        if sh.project_stage_id is None:
            po_stage_id = getattr(po, "project_stage_id", None) if po else None
            pr_stage_id = getattr(pr, "project_stage_id", None) if pr else None
            if po_stage_id:
                sh.project_stage_id = po_stage_id
                update.append("project_stage")
            elif pr_stage_id:
                sh.project_stage_id = pr_stage_id
                update.append("project_stage")

        if sh.project_id is None:
            po_project_id = getattr(po, "project_id", None) if po else None
            pr_project_id = getattr(pr, "project_id", None) if pr else None
            if po_project_id:
                sh.project_id = po_project_id
                update.append("project")
            elif pr_project_id:
                sh.project_id = pr_project_id
                update.append("project")

        # If project still empty, but stage exists — infer project from stage
        if sh.project_id is None and sh.project_stage_id is not None:
            st = getattr(sh, "project_stage", None)
            st_project_id = getattr(st, "project_id", None) if st else None
            if st_project_id:
                sh.project_id = st_project_id
                update.append("project")

        # If order has stage but shipment doesn't and project missing, try order.stage.project
        if sh.project_id is None and getattr(po, "project_stage_id", None) is not None:
            st = getattr(po, "project_stage", None)
            st_project_id = getattr(st, "project_id", None) if st else None
            if st_project_id:
                sh.project_id = st_project_id
                update.append("project")

        if update:
            sh.save(update_fields=list(dict.fromkeys(update)))


def backwards(apps, schema_editor):
    # No-op: keep snapshot fields.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0008_alter_supplierpricelistline_vat_rate"),
        ("projects", "0003_project_delivery_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="projects.project",
                verbose_name="Проект",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="project_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="projects.projectstage",
                verbose_name="Этап проекта",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="projects.project",
                verbose_name="Проект",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="project_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="projects.projectstage",
                verbose_name="Этап проекта",
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
