# Generated by Django 5.0.7 on 2025-12-21 23:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название поставщика')),
                ('inn', models.CharField(blank=True, max_length=64, null=True, verbose_name='ИНН / рег. номер')),
                ('activity', models.CharField(blank=True, default='', max_length=255, verbose_name='Основная деятельность')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='0..5 (5 = лучший)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('status', models.CharField(choices=[('preferred', 'Предпочитаемый'), ('regular', 'Обычный'), ('blocked', 'Блокирован')], default='regular', max_length=20, verbose_name='Статус допуска')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('categories', models.ManyToManyField(blank=True, related_name='suppliers', to='catalog.category', verbose_name='Категории поставляемых материалов')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('position', models.CharField(blank=True, default='', max_length=255, verbose_name='Должность / Роль')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Контакт поставщика',
                'verbose_name_plural': 'Контакты поставщика',
                'ordering': ['person_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название прайса')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Актуально с')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelists', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Прайс-лист поставщика',
                'verbose_name_plural': 'Прайс-листы поставщиков',
                'ordering': ['supplier', '-valid_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(blank=True, default='', max_length=255, verbose_name='Артикул поставщика')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('notes', models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item', verbose_name='Номенклатура')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit', verbose_name='Единица')),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='suppliers.supplierpricelist', verbose_name='Прайс-лист')),
            ],
            options={
                'verbose_name': 'Строка прайса поставщика',
                'verbose_name_plural': 'Строки прайса поставщика',
                'ordering': ['pricelist', 'item'],
            },
        ),
        migrations.CreateModel(
            name='SupplierTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms', models.CharField(blank=True, default='', max_length=255, verbose_name='Условия оплаты')),
                ('min_order_amount', models.CharField(blank=True, default='', max_length=255, verbose_name='Минимальный заказ')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Типовой срок поставки (дн.)')),
                ('delivery_regions', models.CharField(blank=True, default='', max_length=255, verbose_name='Регионы поставки')),
                ('delivery_notes', models.TextField(blank=True, default='', verbose_name='Логистика / Доставка')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Условия поставщика',
                'verbose_name_plural': 'Условия поставщиков',
            },
        ),
    ]
