# Generated by Django 5.0.7 on 2026-01-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpriceline',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Сроки (дн.)'),
        ),
        migrations.AddField(
            model_name='supplierpriceline',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Минимум'),
        ),
        migrations.AddField(
            model_name='supplierpricelist',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Действует до'),
        ),
        migrations.AddField(
            model_name='supplierpricelist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='supplierpricelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='supplierpricelist',
            name='version',
            field=models.CharField(default='1.0', max_length=50, verbose_name='Версия'),
        ),
    ]
